services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: nextjs_frontend
    ports:
      - "3001:3001"
    networks:
      - app-network
    environment:
      - NODE_ENV=production

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: nestjs_backend
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - NODE_ENV=production

networks:
  app-network:
    driver: bridge
